### ISSUE TITLE
Open Source this Repository

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/couchdb-best-practices#22]
@FrancescoK and @bnvk could you have a look and scan the repo for sensitive information?

**Comment by bnvk** [comment]
@jo is the goal to move this information into Docs site I'm working on? It does not look like there is any sensitive information in there to me. Thumbs up on the musicians :wink:

**Comment by jo** [comment]
http://docs.ehealthafrica.org/couchdb-best-practices/

**Comment by jo** [comment]
Maybe we can integrate it?

**Comment by FrancescoK** [comment]
We should. At least reference it.
