### ISSUE TITLE
Useful meta keys section

### ISSUE THREAD

**Issue by karlwestin** [eHealthAfrica/couchdb-best-practices#28]
I can write it, just starting the discussion here. Some things i've found useful

createdDate
modifiedDate
modifiedBy - if several apps are touching the same doc
createdBy - if there's both importers and an app that can create docs
docVersion - to be able to 'live migrate' docs and deal w/ that not all clients get updated at the same time
appVersion - just to see what app versions you have out there writing docs

**Comment by jo** [comment]
Yeah, very useful.

**Comment by jo** [comment]
Also related to #29

**Comment by jo** [comment]
Hi @karlwestin, I added the section: http://docs.ehealthafrica.org/couchdb-best-practices/#useful-meta-keys

I did not add the `appVersion`, because I thought it is not very common, but I am open to get convinced by you :)
