### ISSUE TITLE
about module.exports = function () {}

### ISSUE THREAD

**Issue by fiatjaf** [eHealthAfrica/couchdb-best-practices#36]
In https://github.com/eHealthAfrica/couchdb-best-practices/blob/gh-pages/README.md#modularize-view-code it is said that _"Some features are not supported, for example the assignment of a function"_, but I'm on CouchDB 1.5 and I can assure I'm using a lot of

``` javascript
module.exports = function () {}
```

and they are all working. What is happening?

**Comment by jo** [comment]
You're totally right! CouchDB has updated long time ago from CommonJS 1.1 to [CommonJS 1.1.1](http://wiki.commonjs.org/wiki/Modules/1.1.1).
@caolan has written a comprehensive blog post called [CommonJS modules in CouchDB](http://caolanmcmahon.com/posts/commonjs_modules_in_couchdb/).

Thanks for reporting, I will fix this.
