### ISSUE TITLE
Avoid `/` in `_id`s

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/couchdb-best-practices#39]
Regarding https://github.com/eHealthAfrica/couchdb-best-practices#one-to-n-relations, I'd strongly suggest to avoid using `/`. We do that in Hoodie and it keeps causing quite some headaches. Also, to quote @nycdubliner:

> FOR THE LOVE OF GOD NO `/`.
> (Specifics: Causes issues with our nginx re-write config that we don't have a fix for.)

**Comment by jo** [comment]
Your suggestion?
https://www.youtube.com/watch?v=vhsQPbpR438

**Comment by gr2m** [comment]
use `-` or `_`

**Comment by jo** [comment]
I don't think they are a good fit. :-1: 
The problem is they often occur in the id part.

**Comment by jo** [comment]
But I'm OK with a different seperator

**Comment by gr2m** [comment]
You either use `-` or `_` in your IDs, not both. Just be consistent in your project

**Comment by jo** [comment]
I am in favor of `:` as this is already used in _users.

**Comment by gr2m** [comment]
`:` :+1:
