### ISSUE TITLE
Link section titles 

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/couchdb-best-practices#44]
nice to have: add links to all section headers, like it's done in GitHub READMEs
![screen shot 2015-05-18 at 12 07 50](https://cloud.githubusercontent.com/assets/39992/7678711/96bca37e-fd56-11e4-809d-09e495d70f90.png)

**Comment by jo** [comment]
Use http://bryanbraun.github.io/anchorjs/

**Comment by gr2m** [comment]
super nice, thanks @jo :+1:
