### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by klaemo** [eHealthAfrica/couchdb-best-practices#67]
Minor, minor nit pick:

I suggest setting `font-size` to `16px`.  At the moment the font is quite large (see attached screenshot, proposed `16px` on the left, current `16pt` on the right).

<img width="1440" alt="couch-best-practices-font-size" src="https://cloud.githubusercontent.com/assets/778624/11848411/8aae3674-a422-11e5-87ab-171915a60b12.png">

**Comment by jo** [comment]
Hi @klaemo I love big fonts but I'm willing to accept a pull if you'd like to submit one :)
