### ISSUE TITLE
CouchDB 3 and the couch-per-use "plague"

### ISSUE THREAD

**Issue by fredguth** [eHealthAfrica/couchdb-best-practices#76]
I have 2 questions:
1) Has any of these best practices changed with CouchDB 3?
2) What is your reaction on ["Rule 5: Avoid the database-per-user anti-pattern like the plague"](https://www.ibm.com/blogs/cloud-archive/2019/03/cloudant-best-and-worst-practices-part-1/) _best practice_ from Cloudant?

**Comment by jo** [comment]
The best practices described here are also valid for CouchDB 3. However, I haven't worked with Linked Documents for a while, so this section may be outdated.

The DB-Per-User question is a bit complicated. It depends. The biggest bottleneg here is replication: the CouchDB replicator has its weaknesses when it comes to continuous intra-cluster replication. Here, the individual changes feeds are polled round-robin, which creates a high load. If validate doc update functions are also used, this load increases. Therefore, it may make sense to implement application-specific replication logic. That is, if the application knows when something changes, it can instruct single-shot replications, thus reducing the load.

I'm looking forward to the upcoming new features of CouchDB, especially the per-document access patterns, which would be a big step here.

**Comment by fredguth** [comment]
Thanks for the explanation!
