### ISSUE TITLE
Link failed

### ISSUE THREAD

**Issue by fredguth** [eHealthAfrica/couchdb-best-practices#77]
The reference to "[control access on a per document level](https://wiki.apache.org/couchdb/PerDocumentAuthorization) " is no longer valid.  Do you have a link for this content elsewhere?

**Comment by jo** [comment]
Hi @fredguth, thanks for pointing that out! The old wiki no longer exists and it looks like the content has not been migrated. Work is underway to implement per-document access: https://github.com/apache/couchdb/issues/1524

I have updated the document here.

**Comment by fredguth** [comment]
Sorry to once again contact you via issue.  Is there a tiny project using a crypto box to solve per document authorization?  
I understand all the concepts in theory, but I do not feel confident in applying them because I fear doing something really wrong.  My goal is to offer services with the "translucent database" approach.

**Comment by jo** [comment]
Sadly there is none open sourced I'm aware of. Do you have the concept written somewhere so I can have a look?

**Comment by fredguth** [comment]
I will do that and share with you. I am revisiting a project I developed in 2015-2016 that used pouch/couchdb with one-db-per-user (now defunct). Interestingly, it looks similar (visually) to Immmr, you worked on.

**Comment by fredguth** [comment]
I invited you to [Couchello](https://github.com/fredguth/Couchello) which is intended to be a Demo project for current CouchDB best practices.
